---
strip_channel:
  0:
    gpionum: 21
    count: 680
    invert: 0
    brightness: 255
    strip_type: WS2811_STRIP_GRB
mapping:
  0:
  - input:
      start_address: 1
      total_rgb_channels: 170
    output:
      start_address: 1
      strip_channel: 0
  1:
  - input:
      start_address: 1
      total_rgb_channels: 170
    output:
      start_address: 170
      strip_channel: 0
  2:
  - input:
      start_address: 1
      total_rgb_channels: 170
    output:
      start_address: 340
      strip_channel: 0
  3:
  - input:
      start_address: 1
      total_rgb_channels: 170
    output:
      start_address: 510
      strip_channel: 0